di:
    instance:
        alias:
            geoname: Heartsentwined\Geoname\Service\Geoname
            geoname-cli: Heartsentwined\Cli\Cli
            browser: Heartsentwined\Browser\Factory
        geoname:
            parameters:
                #em: doctrine.entitymanager.orm_default
                cli: geoname-cli
                tmpDir: data/geoname
                cron: '*/15 * * * *'
        geoname-cli:
            parameters:
                templates:
                    section:
                        template: '## %s ##'
                        color: YELLOW
                    task:
                        template: '- %s -'
                        color: BLUE
                    module:
                        template: '[ %s ]'
                        color: GREEN
doctrine:
    driver:
        geoname_driver:
            class: Doctrine\ORM\Mapping\Driver\YamlDriver
            cache: array
            paths:
                - __DIR__/../src/Heartsentwined/Geoname/Entity/Mapping
        orm_default:
            drivers:
                Heartsentwined\Geoname\Entity: geoname_driver
